### ISSUE TITLE
[BUG] - Crash when recording microphone audio with PixelStreaming 2

### ISSUE THREAD

**Issue by tiago1397** [EpicGames/PixelStreamingInfrastructure#665]
**UE Version:**
UE 5.5.4

**Frontend Version:**
UE 5.5.4

**Problem component**
Pixel Streaming 2, Microphone

**Description**
When the browser accesses the microphone through streaming, the application (or editor) immediately crashes. Please check the image for the crash report. The setup to record microphone audio was working well with PixelStreaming original version. 

**Screenshots**
![Image](https://github.com/user-attachments/assets/376d4c2e-9228-4c19-87a9-81b2df345339)

**Platform (please complete the following information):**
 - OS: Windows 11
 - Browser Google Chrome latest version

**Comment by lukehb** [comment]
Hey, we checked in with the team and they said this _was_ a known issue with `5.5.4` but has since been fixed in `5.6`.

In the meantime, you can work around this issue by starting your UE `5.5.4` application with `-PixelStreamingWebRTCDisableStats=1`

**Comment by tiago1397** [comment]
hi @lukehb, I've tried the work around you mentioned but the application is still crashing with the same error

**Comment by lukehb** [comment]
> hi [@lukehb](https://github.com/lukehb), I've tried the work around you mentioned but the application is still crashing with the same error

Sorry @tiago1397 can you try `-PixelStreamingWebRTCDisableStats=true` (not 1, that was an error)
